// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (freebsd && 386) || (freebsd && arm)

package vec

const m___INT_FAST64_FMTd__ = "lld"

const m___INT_FAST64_FMTi__ = "lli"

const m___INT_LEAST64_FMTd__ = "lld"

const m___INT_LEAST64_FMTi__ = "lli"

const m___UINT_FAST64_FMTX__ = "llX"

const m___UINT_FAST64_FMTo__ = "llo"

const m___UINT_FAST64_FMTu__ = "llu"

const m___UINT_FAST64_FMTx__ = "llx"

const m___UINT_FAST64_MAX__ = "18446744073709551615U"

const m___UINT_LEAST64_FMTX__ = "llX"

const m___UINT_LEAST64_FMTo__ = "llo"

const m___UINT_LEAST64_FMTu__ = "llu"

const m___UINT_LEAST64_FMTx__ = "llx"

const m___UINT_LEAST64_MAX__ = "18446744073709551615U"
