// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (linux && amd64) || (linux && arm64) || (linux && loong64) || (linux && ppc64le) || (linux && riscv64) || (linux && s390x) || (netbsd && amd64) || (windows && (amd64 || arm64))

package vec

const m___INTPTR_MAX__ = 0x7fffffffffffffff

const m___PTRDIFF_MAX__ = 0x7fffffffffffffff
