// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (freebsd && 386) || (linux && 386) || (windows && 386)

package vec

const m___LAHF_SAHF__ = 1
