// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (netbsd && amd64) || (openbsd && amd64) || (openbsd && arm64) || (windows && (amd64 || arm64)) || (windows && 386)

package vec

type time_t = Ttime_t
