// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (linux && 386) || (linux && amd64) || (linux && s390x)

package vec

const m_PAGESIZE = 4096

const m_PAGE_SIZE = "PAGESIZE"
