// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && arm64) || (freebsd && arm) || (freebsd && arm64) || (linux && arm64) || (openbsd && arm64)

package vec

const m___ARM_FP16_ARGS = 1

const m___ARM_FP16_FORMAT_IEEE = 1

const m___ARM_NEON = 1
