// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && arm64) || (freebsd && arm64) || (openbsd && arm64)

package vec

const m___ARM_ALIGN_MAX_STACK_PWR = 4

const m___ARM_FEATURE_DIRECTED_ROUNDING = 1

const m___ARM_FEATURE_DIV = 1

const m___ARM_FEATURE_LDREX = 0xF

const m___ARM_FP = 0xE

const m___ARM_NEON_FP = 0xE

const m___ARM_STATE_ZA = 1

const m___ARM_STATE_ZT0 = 1

const m___HAVE_FUNCTION_MULTI_VERSIONING = 1
