// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (linux && 386) || (linux && amd64) || (netbsd && amd64) || (windows && (amd64 || arm64)) || (windows && 386)

package vec

const m___ATOMIC_HLE_ACQUIRE = 65536

const m___ATOMIC_HLE_RELEASE = 131072

const m___LONG_DOUBLE_64__ = 1
