// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (freebsd && amd64) || (linux && amd64) || (netbsd && amd64) || (openbsd && amd64) || (windows && (amd64 || arm64))

package vec

const m___FXSR__ = 1

const m___amd64 = 1

const m___amd64__ = 1

const m___x86_64 = 1

const m___x86_64__ = 1
