// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (linux && 386) || (linux && amd64) || (windows && (amd64 || arm64)) || (windows && 386)

package vec

const m___DECIMAL_BID_FORMAT__ = 1
