// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (freebsd && 386) || (freebsd && amd64) || (freebsd && arm) || (freebsd && arm64) || (linux && loong64) || (openbsd && amd64) || (openbsd && arm64)

package vec

const m___GNUC_PATCHLEVEL__ = 1
