// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (freebsd && arm) || (linux && 386) || (linux && arm) || (windows && (amd64 || arm64)) || (windows && 386)

package vec

type Tldiv_t = struct {
	Fquot int32
	Frem  int32
}

const m___LONG_WIDTH__ = 32

const m___SIZEOF_LONG__ = 4
