// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (windows && (amd64 || arm64)) || (windows && 386)

package vec

import (
	"unsafe"

	"modernc.org/libc"
)

type Tint_fast16_t = int16

type Tuint_fast16_t = uint16

func Xbitmap_set(tls *libc.TLS, bitmap uintptr, position Ti32, value int32) {
	var v1 uintptr
	_ = v1
	if value != 0 {
		v1 = bitmap + uintptr(position/int32(m___CHAR_BIT__))
		*(*Tu8)(unsafe.Pointer(v1)) = Tu8(int32(*(*Tu8)(unsafe.Pointer(v1))) | libc.Int32FromInt32(1)<<(position%libc.Int32FromInt32(m___CHAR_BIT__)))
	} else {
		v1 = bitmap + uintptr(position/int32(m___CHAR_BIT__))
		*(*Tu8)(unsafe.Pointer(v1)) = Tu8(int32(*(*Tu8)(unsafe.Pointer(v1))) & ^(libc.Int32FromInt32(1) << (position % libc.Int32FromInt32(m___CHAR_BIT__))))
	}
}

const m_PRIXFAST64 = "PRIX64"

const m_PRIXLEAST64 = "PRIX64"

const m_PRIdFAST64 = "PRId64"

const m_PRIdLEAST64 = "PRId64"

const m_PRIiFAST64 = "PRIi64"

const m_PRIiLEAST64 = "PRIi64"

const m_PRIoFAST64 = "PRIo64"

const m_PRIoLEAST64 = "PRIo64"

const m_PRIuFAST64 = "PRIu64"

const m_PRIuLEAST64 = "PRIu64"

const m_PRIxFAST64 = "PRIx64"

const m_PRIxLEAST64 = "PRIx64"
