// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (freebsd && 386) || (freebsd && amd64) || (openbsd && amd64)

package vec

const m___BITINT_MAXWIDTH__ = 8388608

const m___NO_MATH_INLINES = 1
