// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (freebsd && amd64) || (freebsd && arm) || (freebsd && arm64) || (linux && 386) || (linux && amd64) || (linux && arm) || (linux && arm64) || (linux && loong64) || (linux && ppc64le) || (linux && riscv64) || (linux && s390x) || (windows && (amd64 || arm64)) || (windows && 386)

package vec

const m_INT_FAST32_MAX = "INT32_MAX"

const m_INT_FAST32_MIN = "INT32_MIN"

const m_INT_FAST64_MAX = "INT64_MAX"

const m_INT_FAST64_MIN = "INT64_MIN"

const m_UINT_FAST32_MAX = "UINT32_MAX"

const m_UINT_FAST64_MAX = "UINT64_MAX"
