// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (linux && loong64) || (linux && ppc64le)

package vec

const m___FLOAT128_TYPE__ = 1

const m___GNUC__ = 14

const m___GXX_ABI_VERSION = 1019

const m___builtin_copysignq = "__builtin_copysignf128"

const m___builtin_fabsq = "__builtin_fabsf128"

const m___builtin_huge_valq = "__builtin_huge_valf128"

const m___builtin_infq = "__builtin_inff128"

const m___builtin_nanq = "__builtin_nanf128"

const m___builtin_nansq = "__builtin_nansf128"
