// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (freebsd && amd64) || (freebsd && arm) || (freebsd && arm64) || (linux && amd64) || (linux && arm64) || (linux && riscv64) || (openbsd && amd64) || (openbsd && arm64)

package vec

const m___FLT16_DECIMAL_DIG__ = 5

const m___FLT16_DIG__ = 3

const m___FLT16_HAS_DENORM__ = 1

const m___FLT16_HAS_INFINITY__ = 1

const m___FLT16_HAS_QUIET_NAN__ = 1

const m___FLT16_MANT_DIG__ = 11

const m___FLT16_MAX_10_EXP__ = 4

const m___FLT16_MAX_EXP__ = 16
