// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (linux && amd64) || (linux && arm64) || (linux && riscv64)

package vec

const m___FLT16_DENORM_MIN__ = 5.96046447753906250000000000000000000e-8

const m___FLT16_EPSILON__ = 9.76562500000000000000000000000000000e-4

const m___FLT16_MAX__ = 6.55040000000000000000000000000000000e+4

const m___FLT16_MIN__ = 6.10351562500000000000000000000000000e-5

const m___FLT16_NORM_MAX__ = 6.55040000000000000000000000000000000e+4
