// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (freebsd && amd64) || (linux && 386) || (linux && amd64) || (linux && ppc64le) || (netbsd && amd64) || (openbsd && amd64) || (windows && (amd64 || arm64)) || (windows && 386)

package vec

const m___SIZEOF_FLOAT128__ = 16
