// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (linux && 386) || (windows && 386)

package vec

const m___SIZEOF_FLOAT80__ = 12

const m___code_model_32__ = 1
