// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (netbsd && amd64)

package vec

type Texception = struct {
	Ftype1  int32
	Fname   uintptr
	Farg1   float64
	Farg2   float64
	Fretval float64
}

type exception = Texception

const m_DBL_DIG = "__DBL_DIG__"

const m_DBL_EPSILON = "__DBL_EPSILON__"

const m_DBL_MANT_DIG = "__DBL_MANT_DIG__"

const m_DBL_MAX = "__DBL_MAX__"

const m_DBL_MAX_10_EXP = "__DBL_MAX_10_EXP__"

const m_DBL_MAX_EXP = "__DBL_MAX_EXP__"

const m_DBL_MIN = "__DBL_MIN__"

const m_DBL_MIN_10_EXP = "__DBL_MIN_10_EXP__"

const m_DBL_MIN_EXP = "__DBL_MIN_EXP__"

const m_DOMAIN = 1

const m_ENOATTR = 93

const m_FLT_DIG = "__FLT_DIG__"

const m_FLT_EPSILON = "__FLT_EPSILON__"

const m_FLT_EVAL_METHOD = "__FLT_EVAL_METHOD__"

const m_FLT_MANT_DIG = "__FLT_MANT_DIG__"

const m_FLT_MAX = "__FLT_MAX__"

const m_FLT_MAX_10_EXP = "__FLT_MAX_10_EXP__"

const m_FLT_MAX_EXP = "__FLT_MAX_EXP__"

const m_FLT_MIN = "__FLT_MIN__"

const m_FLT_MIN_10_EXP = "__FLT_MIN_10_EXP__"

const m_FLT_MIN_EXP = "__FLT_MIN_EXP__"

const m_FLT_RADIX = "__FLT_RADIX__"

const m_INTMAX_MAX = "__INTMAX_MAX__"

const m_INTPTR_MAX = "__INTPTR_MAX__"

const m_MB_CUR_MAX = "__mb_cur_max"

const m_OVERFLOW = 3

const m_PLOSS = 6

const m_PTRDIFF_MAX = "__PTRDIFF_MAX__"

const m_SING = 2

const m_SIZE_MAX = "__SIZE_MAX__"

const m_TLOSS = 5

const m_UINTMAX_MAX = "__UINTMAX_MAX__"

const m_UINTPTR_MAX = "__UINTPTR_MAX__"

const m_UNDERFLOW = 4

const m_X_TLOSS = 1.41484755040568800000e+16

type pthread_attr_t = Tpthread_attr_t
