// Code generated by modernc.org/undup from the per-target sqlite_*.go files; DO NOT EDIT.

//go:build cosmo

package sqlite3

const __GCC_ATOMIC_BOOL_LOCK_FREE = 2

const __GCC_ATOMIC_CHAR16_T_LOCK_FREE = 2

const __GCC_ATOMIC_CHAR_LOCK_FREE = 2

const __GCC_ATOMIC_SHORT_LOCK_FREE = 2

const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 = 1

const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 = 1
