// Code generated by modernc.org/undup from the per-target sqlite_*.go files; DO NOT EDIT.

//go:build cosmo

package sqlite3

const FP_INFINITE = 1

const RTLD_LOCAL = 0

const __unix = 1

const unix = 1
