// Code generated by modernc.org/undup from the per-target sqlite_*.go files; DO NOT EDIT.

//go:build cosmo

package sqlite3

const __DECIMAL_DIG__ = 17

const __LDBL_DECIMAL_DIG__ = 17

const __LDBL_DIG__ = 15

const __LDBL_MANT_DIG__ = 53

const __LDBL_MAX_10_EXP__ = 308

const __LDBL_MAX_EXP__ = 1024

const __LDBL_MIN_10_EXP__ = -307

const __LDBL_MIN_EXP__ = -1021
