// Code generated by modernc.org/undup from the per-target sqlite_*.go files; DO NOT EDIT.

//go:build cosmo

package sqlite3

const __INT_FAST8_MAX__ = 127

const __INT_FAST8_WIDTH__ = 8

const __UINT_FAST8_MAX__ = 255

type mode_t = Tmode_t

type off_t = Toff_t

type pid_t = Tpid_t
